### ISSUE TITLE
Source event attributes do not save in the cohort builder

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/WebAPI#2185] opened 2023-01-20 10:04 UTC
### Expected behavior
As a user, I expect that after clicking the "Save" button, the cohort will be saved as is, even I have not chosen a concept for the "source" attribute. If the attributes are not valid, they should not present on the dropdown lists

### Actual behavior
The attributes do not present in the request payload and in the saved cohort definition.
_Payer Plan Period_ attributes are in the payload but they do not present on the screen after cohort saving.

### Steps to reproduce behavior
1. Go to Cohort Definitions and create a new cohort
2. To initial event add the following events with their attributes:
```
- Condition Occurrence -> Condition Source Concept
- Death -> Cause of Death Source Concept Criteria
- Device Exposure -> Device Source Concept Criteria
- Drug Exposure -> Drug Source Concept Criteria
- Measurement -> Measurement Source Concept Criteria
- Observation -> Observation Source Concept Criteria
- Payer Plan Period -> Payer Source Concept Criteria, Plan Source Concept Criteria, Sponsor Source Concept Criteria, Stop Reason Source Concept Criteria
- Procedure Occurrence -> Procedure Source Concept Criteria
- Visit Occurrence, Details -> Visit Source Concept Criteria
```
4. Save the cohort definition

**Comment by chrisknoll** [comment] 2023-01-21 06:18
This is actually expected behavior:   if you don't specify a concept set (such that it says 'any source concept' there is no value (ie: null) saved with the attribute, and null values are not serialized in the payload. This is because there would be no way to 'remove' a null value later (a null mean that it isn't present, and there fore you didn't specify the paramater).   

On the UI side we create a sort of 'proxy' for when you add the attribute, the proxy is there to accept the selection. but when it's saved, the proxy because the actual value (a non-selection turns to null) and therefore it appears that you haven't seleted anything.

So this is basically a limitation of the technology / data structures.  When you say 'any concept' in those source fields, you are basically not restricting on anything in that field, so the fact that it doesn't say 'any concept' anymore doesn't change the logic.

Closing this but feel free to discuss further if there is something more that I am missing.

**Closed by chrisknoll** 2023-01-21 06:18 UTC
