### ISSUE TITLE
If you import an LDAP user, put the username in the WebAPI DB

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#990] opened 2019-03-27 08:36 UTC
![Screenshot from 2019-03-27 17-26-33](https://user-images.githubusercontent.com/16149781/55061077-354cb400-50b6-11e9-8b8f-a9bbf6d1170c.png)

Before importing an LDAP user, import username.

![Screenshot from 2019-03-27 17-28-37](https://user-images.githubusercontent.com/16149781/55061275-a724fd80-50b6-11e9-8a04-646726e5d6c3.png)

However, it seems that the username is not stored anywhere in the ```SEC_USER``` table. How about using the username in the ```NAME``` column in the ```SEC_USER``` table?

**Comment by pavgra** [comment] 2019-03-27 12:51
Duplicate of https://github.com/OHDSI/Atlas/issues/1289

**Closed by pavgra** 2019-03-27 12:51 UTC
