### ISSUE TITLE
Error in hive sql command

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#1749] opened 2021-01-19 09:04 UTC
Error occures during generating cohort

```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; 
bad SQL grammar [DELETE FROM omop_orc_results_280.cohort_inclusion WHERE cohort_definition_id = 77081;]; 
nested exception is org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: 
FAILED: ParseException line 1:84 cannot recognize input near '77081' ';' '<EOF>' in constant
```

**Comment by chrisknoll** [comment] 2021-01-19 13:22
I believe this is an example where we need to translate and `SplitSql` the delete command.

Possibly a dupe of #1730.

**Comment by ssuvorov-fls** [comment] 2021-01-21 06:10
closed via #1730

**Closed** 2021-01-21 06:10 UTC
