### ISSUE TITLE
Failed to save Custom Feature

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1300] opened 2019-08-19 22:50 UTC
When creating a new Custom Feature (ie: where you specify SQL), if you type in any text into the textbox and attempt to save the feature, it returns an 'Opps! something went wrong!' without any further information.

Debugging this locally, no error is presented in the console output.

The last logged message is:
```
Hibernate: select next value for ohdsi.fe_analysis_sequence
```
But, no other error is reported after.

The log excerpt is:
```
2019-08-19 18:42:03.570 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Participating in existing transaction
Hibernate: select feanalysis0_.id as id1_26_0_, feanalysis0_.created_by_id as created11_26_0_, feanalysis0_.created_date as created_2_26_0_, feanalysis0_.modified_by_id as modifie12_26_0_, feanalysis0_.modified_date as modified3_26_0_, feanalysis0_.descr as descr4_26_0_, feanalysis0_.domain as domain5_26_0_, feanalysis0_.is_locked as is_locke6_26_0_, feanalysis0_.name as name7_26_0_, feanalysis0_.design as design8_26_0_, feanalysis0_.stat_type as stat_typ9_26_0_, feanalysis0_.type as type10_26_0_ from ohdsi.fe_analysis feanalysis0_ where feanalysis0_.id=? and CASE WHEN feanalysis0_.type = 'CRITERIA_SET' THEN CONCAT(feanalysis0_.type,'_',feanalysis0_.stat_type)ELSE feanalysis0_.type END is not null
Hibernate: select next value for ohdsi.fe_analysis_sequence
2019-08-19 18:42:03.574 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Participating transaction failed - marking existing transaction as rollback-only
2019-08-19 18:42:03.574 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Setting JPA transaction on EntityManager [SessionImpl(883508293<open>)] rollback-only
2019-08-19 18:42:03.574 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Initiating transaction rollback
2019-08-19 18:42:03.574 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Rolling back JPA transaction on EntityManager [SessionImpl(883508293<open>)]
2019-08-19 18:42:03.575 DEBUG http-nio-8080-exec-4 org.springframework.orm.jpa.JpaTransactionManager -  - Closing JPA EntityManager [SessionImpl(883508293<open>)] after transaction
```

After the sequence is queried, the transaction is rolled back, but I can find no reason given.

**Comment by chrisknoll** [comment] 2019-08-20 12:47
While this doesn't seem to be a problem on 2.7.3, this is an issue on current master branch.

**Comment by anthonysena** [comment] 2019-08-20 18:20
@chrisknoll - per our discussion, let's see if we can check this on the current master code base.

**Comment by anthonysena** [comment] 2020-09-15 12:17
Closing since I'm unable to reproduce this on the current master code base.

**Closed by anthonysena** 2020-09-15 12:17 UTC
