### ISSUE TITLE
Failed Heracles report generation for BQ

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#1063] opened 2019-04-23 12:04 UTC
Failed Heracles report generation for BQ

![bq_heracles_report](https://user-images.githubusercontent.com/804934/56579499-f89eaa80-65d8-11e9-8344-3b5b6b36b38f.png)

**Comment by anthonysena** [comment] 2019-07-02 19:07
@spbima - looking for some feedback to know if this issue is still present with the v2.7.2 release or if we can close this out?

**Comment by olga-ganina** [comment] 2020-01-14 10:53
cannot reproduce anymore, so closing this one

**Closed by olga-ganina** 2020-01-14 10:53 UTC
Labels: bug, cohort, question
