### ISSUE TITLE
Vocabularies: RC/DRC counts show "timeout"

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#644] opened 2018-10-10 13:17 UTC
1. Go to Search
2. Search for something
3. Observer results and 'timeout' in RC/DRC fields

![image](https://user-images.githubusercontent.com/4144173/46738866-e5189b80-cca7-11e8-9223-20df75d23623.png)

**Comment by pavgra** [comment] 2018-10-16 21:10
@konstjar , seems to work in latest master. If this is not related to maintenance, pls provide version. Otherwise, close the issue.

**Comment by fdefalco** [comment] 2018-10-17 05:12
This behavior can occur when the WebAPI is first started.  The WebAPI caches the counts in memory at startup, but this usually takes a few minutes to complete.  When the cache is empty the query runs on the database in real time to obtain the RC and DRC.  If that query takes longer than allowed by the ajax timeout setting then this 'timeout' message will appear.

**Comment by pavgra** [comment] 2018-11-12 15:51
Seems to be not reproducible

**Closed by pavgra** 2018-11-12 15:51 UTC
