### ISSUE TITLE
Exceptions when generating full analysis for old cdm schemas

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#1148] opened 2019-05-30 11:28 UTC
org.springframework.batch.core.step.AbstractStep -  - Encountered an error executing step coAnalysisJob
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLExcepn_id does not exist
  Hint: Perhaps you meant to reference the column "vo1.person_id".
 ...org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet.execute(CohortAnalysisTasklet.java:95)

AnalysisJob
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLExcepcost" does not exist
...org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet.execute(CohortAnalysisTasklet.java:95)

**Comment by pavgra** [comment] 2019-05-30 12:20
@ssuvorov-fls , please attach design json and used source description (dbms, cdm version)

**Comment by ssuvorov-fls** [comment] 2019-05-30 12:28
design - [source.json.zip](https://github.com/OHDSI/WebAPI/files/3236975/source.json.zip)
source jdbc url - jdbc:postgresql://odysseusovh02.odysseusinc.com:5432/cdm_v500_synpuf_v101_110k
vocabulary version - v5.0 22-SEP-16

**Comment by anthonysena** [comment] 2019-12-24 13:56
Closing - unable to reproduce on 2.7.4

**Closed by anthonysena** 2019-12-24 13:56 UTC
Labels: bug
