### ISSUE TITLE
Add checking and fixing duplicate keys while migration

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#978] opened 2019-03-18 14:06 UTC
After update version Atlas from 2.4.5 to 2.7.0 it not started with the error "Could not create unique index schema_version_pk"

![migration1](https://user-images.githubusercontent.com/804934/54535416-8c100a80-499f-11e9-8e28-12397c2588d4.jpg)

because there are several entries with the same id

![migration2](https://user-images.githubusercontent.com/804934/54535438-96ca9f80-499f-11e9-9749-b7c1f5e8dae9.jpg)

To solve the problem, the identifiers were updated with a value of max + 1

**Comment by chrisknoll** [comment] 2019-03-18 14:16
That's strange: version_rank and installed_rank should absolutely be unique. From my understanding of Flyway, when the application starts and invokes `migrate`, all new migrations get recorded in schema_version with a new version_rank.   The only way I can imagine that you get duplicate records in that table is that those records were manually inserted into that table?

Can you confirm what database vendor you are using to host webAPI, and can you please provide some steps to reproduce (ie: did you do some kind of backup/restore operation to get the database to be the v2.4.5 version)

**Comment by spbima** [comment] 2019-03-25 09:38
In 2.4.5, the primary key _schema_version_pk_ was for the _version_ column. 
But in version 2.5 or higher _schema_version_pk_ creates a constraint for the _installed_rank_ column

**Comment by spbima** [comment] 2019-03-25 10:18
workaround 

```
UPDATE webapi.schema_version 
SET installed_rank = (SELECT max(installed_rank) + 1 FROM webapi.schema_version)
WHERE installed_rank = 54 
AND version = '2.3.0.20180427114800'
```

**Comment by anthonysena** [comment] 2019-07-02 18:58
This is likely due to testing flyway scripts and not a bug with the flyway mechanism. Closing this issue but if it persists, let's revisit. Thanks!

**Closed by anthonysena** 2019-07-02 18:58 UTC
