### ISSUE TITLE
Violation of unique key constraint for SEC_PERMISSION in SQL Server

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#864] opened 2019-02-26 01:01 UTC
During WebAPI migration, a duplicate insertion of the same value occurred in the SEC_PERMISSION table.

![screenshot from 2019-02-26 10-17-00](https://user-images.githubusercontent.com/16149781/53380238-0b697a00-39b0-11e9-9fd7-54dc818bae91.png)
![screenshot from 2019-02-26 09-47-36](https://user-images.githubusercontent.com/16149781/53379804-68643080-39ae-11e9-833e-a9d3691783c9.png)
![screenshot from 2019-02-26 09-47-41](https://user-images.githubusercontent.com/16149781/53379807-6b5f2100-39ae-11e9-964d-28c17606ddb5.png)

Maybe it will only be affected by the recently updated ```master``` branch.

**Comment by wivern** [comment] 2019-03-04 15:09
Issue with Permission ID was fixed in #886 but sequence might still remains in inconsistent state.
To set sequence to a proper value you may use following SQL code:
`select max(id)+1 from webapi_master.sec_permission;`
and then alter sequence with new value:
`alter sequence webapi_master.sec_permission_id_seq restart with MAXID`
replace MAXID with the actual value returned by the first query.

**Comment by pavgra** [comment] 2019-03-04 22:36
Closed since the cause of the issue was fixed and migration solution was provided

**Closed by pavgra** 2019-03-04 22:36 UTC
