### ISSUE TITLE
Invocation of /mapped raises com.microsoft.sqlserver.jdbc.SQLServerException 

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#125] opened 2016-08-29 16:59 UTC
Invocation of `/mapped` [`WebAPI/ohdsi_west_pending/vocabulary/lookup/mapped`] throws `com.microsoft.sqlserver.jdbc.SQLServerException`. 

Cause: "Invalid object name 'concept'.

Interpretation: `concept` without table qualifier causes SQL grammar issue.

Proposed fix: add appropriate table qualifier to associated SQL script file  `vocabulary/sql/getMappedsourcecodes.sql`.

**Comment by t-abdul-basser** [comment] 2016-08-31 15:49
Related to [Atlas Issue #194](https://github.com/OHDSI/Atlas/issues/194)

**Comment by MaximMoinat** [comment] 2016-09-07 12:09
I have the exact same problem and think that it is caused by an error in [getMappedSourcecodes.sql ](https://github.com/OHDSI/WebAPI/blob/aca171ebf37a1f44cf01829983ac6632b8042821/src/main/resources/resources/vocabulary/sql/getMappedSourcecodes.sql)
Line 5 should specify the cdm_schema (just like for the other tables):
`from @CDM_schema.concept`

Is this right?

**Comment by chrisknoll** [comment] 2016-09-07 12:30
That's correct, all the tables in our queries should be fully qualified.  We'll implement a fix for this.

**Comment by t-abdul-basser** [comment] 2016-09-07 12:34
Yes, there is an outstanding [PR #126] (https://github.com/OHDSI/WebAPI/pull/126) that addresses this.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Sep 7, 2016 at 8:09 AM -0400, "Maxim Moinat" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the exact same problem and think that it is caused by an error in getMappedSourcecodes.sql <https://github.com/OHDSI/WebAPI/blob/aca171ebf37a1f44cf01829983ac6632b8042821/src/main/resources/resources/vocabulary/sql/getMappedSourcecodes.sql>
Line 5 should specify the cdm_schema (just like for the other tables):
from @CDM_schema.concept

Is this right?

**Closed** 2016-09-07 18:19 UTC
