### ISSUE TITLE
Clear Server Cache button in ATLAS does not work

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#2274] opened 2023-05-18 13:31 UTC
### Expected behaviour
ATLAS has "Clear Server Cache" button on Configuration page. Expected that endpoint is present and it clears all in-memory cache and truncates "cdm_cache" table in application database. Maybe anything else?

### Actual behavior
Clicking it request goes to WebAPI/cache/clear endpoint that does not exist.  404 comes as response.
API Documentation does not show the endpoint too: http://webapidoc.ohdsi.org

### Steps to reproduce behavior
1. Enable authentication in ATLAS/WebAPI
2. Open Configuration page with "admin" role
3. Click "Clear Server Cache" button

**Comment by chrisknoll** [comment] 2023-05-18 15:03
Possible dupe of https://github.com/OHDSI/Atlas/issues/2847.

**Comment by anthonysena** [comment] 2023-12-19 14:30
For reference, we're referring to this button:

![Image](https://github.com/OHDSI/WebAPI/assets/12902366/462b0ca1-f758-4610-a6fd-7de50893c4c4)

The proposed behavior should be: clear all results from the WebAPI `cdm_cache` and `achilles_results_cache` tables. This would work across all cached data sources configured in WebAPI. Perhaps we rename this button "Clear WebAPI cache"?

_Question: should this only clear the cached data in the WebAPI database and/or the CDM(s) results table(s)?_

For this button:

![Image](https://github.com/OHDSI/WebAPI/assets/12902366/28c20155-60a7-4300-84b2-47b61d4e0b05)

We'd clear the table that holds the `achilles_record_count` and re-build and re-cache this information in the WebAPI database? Perhaps we need to rename this "refresh record count cache"?

**Comment by anthonysena** [comment] 2024-06-25 13:22
Noting the WebAPI endpoints for the buttons above:

- Clear Server Cache: `WebAPI/cache/clear`
- Data Source Refresh: `WebAPI/cdmresults/<sourceKey>/refreshCache`

**Closed** 2024-11-27 14:37 UTC
