### ISSUE TITLE
Sudden unlogin during session

### ISSUE THREAD

**Issue by anemniugin** [OHDSI/WebAPI#1198] opened 2019-06-17 14:04 UTC
Without any logic.
When I work in 
QA Environment Atlas
with my account 

at random time I can see message that I have to log in (again).
It could be 3-4 times in minute

**Comment by wivern** [comment] 2019-06-19 09:41
This issue probably is not UI issue with unexpected logout itself.
But more about behavior under hard load.
First, there is limit for simultaneously running jobs, currently 100 jobs can run at the same time.
When number of requested jobs exceeds this limit jobs stored to the queue. 
Next issue is about Tomcat connection executors pool which is also limited.
May be there is some correlation between spring batch threads, tomcat threads and docker threads.
Anyway this couldn't be solved simply by adding magician couple of code lines.
My suggestion is to:
1. discuss ability to add some more diagnostics tools e.g. Moskito
1. discuss any architecture solutions to make Atlas be more fault tolerant

**Comment by chrisknoll** [comment] 2019-06-19 12:44
Sorry, I am confused: what does background batch jobs have to do with the session timeouts with the user's session?

My understanding on what could lead to this behavior is:
1. a  new tab is opened signaling a new login request, which invalidates an existing session in the original tab. (this may have been addressed, but may not be a complete fix)
2. a configuration of the session timeout in WebAPI which causes the session to timeout faster than the user expects.

Should we query what configuration @anemniugin has for these settings, and also if there was hard load at the time the sessions were being reset?

**Comment by anthonysena** [comment] 2019-07-02 17:25
I've labelled this a bug but also am noting here that it is not very clear on how we might reproduce this issue at this point. If there are further details to share, please add them to this issue so that we can find the root cause. 

Related question: where is the global session timeout configured? I see references for Hikari and Kerberos in [application.properties](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/application.properties#L171). I'd imagine these are using the defaults from Shiro but would be worthwhile to note how this is configured and how to override the settings.

**Comment by olga-ganina** [comment] 2020-01-10 15:46
We haven't seen this problem for several months already so I suggest to close this one.

**Closed by olga-ganina** 2020-01-10 15:46 UTC
Labels: bug, system
