### ISSUE TITLE
User should be log outed right away if there was another login with the same credentials

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1810] opened 2021-03-05 09:52 UTC
Web api 2.8(also 2.7)
### Expected behavior
The first session has been stopped  - the user was log outed

### Actual behavior
The user still able to do some action, logout happens after some timeout(~5 min). 

### Steps to reproduce behavior
1)Log in by the user
2)Log in by the same user from another IP/browser/VPN

**Comment by OdysseusMark** [comment] 2021-03-12 09:10
https://github.com/OHDSI/WebAPI/pull/437

**Comment by KSadomtsev** [comment] 2021-03-24 11:13
In the next releases, we have to think about a redesign of an access/refresh token approach

**Comment by alondhe** [comment] 2021-03-24 17:43
I actually see this working in our environment when I log into Atlas, and then use ROhdsiWebApi and use the AD auth. My Atlas session token is expired.

**Comment by chrisknoll** [comment] 2021-03-24 18:25
> My Atlas session token is expired.

Unfortunately, this is a feature, not a bug.  What we're planning to try for 2.9 is to expose a 'copy token' button next to your name in the header of Atlas so that you can copy your auth token to clipboard, but then paste it into a call in your R session that will 'establish your identity' to the WebAPI calls, so that you don't do any authentication at all (think of it as an authentication shortcut). That way your Atlas authentication will share the R session's authetnication and there will not be a double-login causing the atlas session to be forcibly closed.

**Comment by alondhe** [comment] 2021-03-24 20:58
@chrisknoll I didn't mean to convey that I found this to be a problem -- I'm totally fine with the security model only allowing me to use Atlas or ROhdsiWebApi, and not simultaneously.

**Comment by anthonysena** [comment] 2022-05-03 18:46
I'm closing this noting that the current behavior is expected. I'm also linking this issue to #1884 for consideration.

**Closed by anthonysena** 2022-05-03 18:46 UTC
Labels: bug
