### ISSUE TITLE
java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map

### ISSUE THREAD

**Issue by yuikns** [OHDSI/WebAPI#194] opened 2017-03-18 14:41 UTC
I am using version 2.0, If I use `tomcat-8.5.11` as container, it will throw exception as above.

The reason could be found [here](http://stackoverflow.com/questions/39214853).

A solution is switching to tomcat 7 or using spring boot instead.

**Comment by chrisknoll** [comment] 2017-03-18 16:44
We should make sure that we run on tomcat 8, so I'll leave this open until we can confirm that it works.

**Comment by ErezYehuda** [comment] 2017-12-07 16:34
@yuikns That dependency conflict does appear to be the cause of this, though the solution to add an exclusion to pom.xml doesn't seem to work, as jersey-core included a copy of jsr311-api in its .jar until v1.19 (WebAPI currently resolves to v1.13 as far as I can tell).

The dependency chain starts with com.microsoft.sqlserver:mssql-jdbc. Changing it from version 6.1.0.jre8 to 6.2.0.jre8 seems to bump the required jersey-core version to 1.19. I'm still working on getting the most recent version of WebAPI going on Linux, so I haven't been able to test that, but that appears to be an independent issue (and seems to tomcat versions).

**Comment by chrisknoll** [comment] 2017-12-07 19:30
Hi, Everyone,
 Thank you so much for looking into the details of these types of errors.  There's so many dependencies listed for WebAPI, it's starting to become a nightmare when different dependencies ask for different version of the same library.  

If anyone is so inclined, if there's a way to evaluate our current dependencies and look for ways to update them such that the different dependencies depend on the same versions of the shared libraries, then maybe we can make an effort to clean up our pom.xml so that all the dependencies depend on the same versions of the shared libraries.  

I think we're just slightly behind on spring boot (curent is 1.5.6, and I believe latest is 1.5.9), so I think we're up-to-date with those references, but there's other libraries (like jdbc, logging, security etc) which may introduce dependency conflicts to spring boot/javax-rs, etc.  I was just working on an external library for circe-be and I foudn that I had to down-grade the jackson JSON databind libraries a bit to keep in line with what WebAPI uses.  Maybe there's more cases where we need to ensure compatibility between dependencies?

**Comment by MaximMoinat** [comment] 2018-02-09 12:34
We encountered the same error on one machine. The fix proposed by @ErezYehuda (`com.microsoft.sqlserver:mssql-jdbc` to 6.**2**.0.jre8) solved our problem. Thanks!
 
Can we change this dependency version in the next release of Atlas? Or would that introduce problems for the people using mssql?

**Comment by chrisknoll** [comment] 2018-02-09 15:00
This change has been made in master and will be released in the 2.3 release (which should be late February).
https://github.com/OHDSI/WebAPI/blob/c92863dbdd5cec90c5e17c29368b91f9b703c6b9/pom.xml#L374

**Closed** 2018-10-29 14:05 UTC
