### ISSUE TITLE
Cohort generations become zombie after 20 parallel executions were started

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#469] opened 2018-06-07 20:29 UTC
Due to:
```
taskExecutor.setMaxPoolSize(20);//TODO
```
all new cohort generations (and not only) become zombie after 20 executions were kicked off.
(https://stackoverflow.com/questions/17659510/core-pool-size-vs-maximum-pool-size-in-threadpoolexecutor)

![image](https://user-images.githubusercontent.com/10010071/41124380-ccaffcf4-6a6f-11e8-85cf-0fe36ab0972e.png)
![image](https://user-images.githubusercontent.com/10010071/41124503-29b3cb6a-6a70-11e8-85f7-7c86210d5e4b.png)

@fdefalco , @chrisknoll , I guess you should have faced this issue - is there any background to know?

**Comment by pavgra** [comment] 2018-06-07 21:02
Default behavior is just to abort jobs overcoming limit, so exceptional situation cannot even be found in logs. I believe this should be changed too
![image](https://user-images.githubusercontent.com/10010071/41126140-93baf8e0-6a74-11e8-868d-079d7a92ed4f.png)

**Comment by chrisknoll** [comment] 2018-06-07 21:02
No, haven't seen things become zombies, but I feel like I have seen cohort generations sit in 'Pending' status but then eventually flip over to running (which could be waiting for a pool thread to become available)...

**Comment by pavgra** [comment] 2018-06-08 14:48
Ok, seems like the pool itself was not a problem. I see three issues:
- `corePoolSize` is not configurable (so I cannot set more than 10 threads to be executed in parallel)
- When a person lacks permission for a cohort generation using some data source, the generation button is still available (not blocked) and goes into processing state after click. So user thinks that she kicked off execution while in fact there is exception in background and after page refresh button is available for click again
- The method, which handles `/cohortdefinition/{id}/generate/{sourceKey}`, is not Transactional, so it is possible that a record in `cohort_generation_info` is created, but batch job for the generation fails to start. So this means that `/info` endpoint shows that job is running, whereas in fact it does not. So the cohort is stuck - you can not click it anymore (I have such examples in my DB)

**Comment by chrisknoll** [comment] 2018-06-08 15:53
> The method, which handles /cohortdefinition/{id}/generate/{sourceKey}, is not Transactional, 

It's true that the method is not transnational, but there is a transactionTemplate in play that wraps the JPA calls so that lazy loading works as intended.  However, the transaction that encloses JPA needed to be independent of calling this.jobTemplate.launch() because (if I recall correctly) the .launch() call would fail stating that there was a current transaction.  This looks like a hack, but that's how I worked around calling the .launch() from within the servlet context.  If you have a better approach, please feel free.

**Comment by pavgra** [comment] 2018-06-08 16:01
> PA needed to be independent of calling this.jobTemplate.launch() 
Due to this we (can) have inconsistent state

**Comment by chrisknoll** [comment] 2018-06-08 17:17
yes, I get that.  does the job launch fail silently, or is there some way to check that the launch was successful and if not reverse the JPA update?  Like I said, I thought wrapping the whole thing in a transaction would be good to have the JPA update and the spring batch launch all-or-nothing, but as I recall (I could be wrong) you cuoldn't wrap the launch() in an existing transaction. If that is no longer the case, I think the proper solution is to do as you describe: wrap the entire call in @Transactional annotation.

**Comment by anthonysena** [comment] 2018-10-29 17:19
Closed via #471, #472, OHDSI/Atlas#738

**Closed by anthonysena** 2018-10-29 17:19 UTC
