### ISSUE TITLE
Possible bug: Measurements in Achilles drilldown reports do not display a summary statistics

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/WebAPI#1218] opened 2019-06-28 10:56 UTC
Measurement: Blood count; complete (CBC), automated (Hgb, Hct, RBC, WBC and platelet count) and automated differential WBC count Drilldown Report
SynPUF 110k

![image_2019_06_26T19_27_34_002Z](https://user-images.githubusercontent.com/51909928/60337693-718cfa80-99ac-11e9-99a9-a1a35a63c27d.png)

**Comment by anthonysena** [comment] 2019-07-02 19:18
@pavgra can you take a look in the SynPuf database to see if this particular measurement concept has non-null values in any of corresponding unit or values columns for these rows in SynPuf?

**Comment by wivern** [comment] 2020-02-07 14:25
@anthonysena There are no records with the non-null `unit_concept_id` field in the SynPUF's measurement table. As this column marked as optional therefore it's not a bug I guess.
However, I'd like to make a little fix for a "Measurement Records by Unit" window. With it, "no matching concept" should be displayed instead of an empty field.

**Closed** 2020-02-12 20:18 UTC
Labels: data sources, question
